# Generated by Django 4.2.11 on 2024-04-13 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_reserve'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserve',
        ),
    ]
